#!/usr/bin/env python3
"""Apply Web Emu speed, battery-save and status integrations to the mGBA SDK."""
from pathlib import Path
p=Path("upstream/src/mgba.sdk.ts")
s=p.read_text(encoding="utf-8")
def replace_count(before, after, count=1):
    global s
    seen=s.count(before)
    if seen != count:
        raise RuntimeError(f"Upstream SDK changed: expected {count} for {before[:75]!r}, found {seen}")
    s=s.replace(before, after)
replace_count("  let coreRate = 0;", "  let coreRate = 0;\n  let speedMultiplier = 1;\n  let autoSaveEnabled = true;\n  let lastDrawTime = 0;\n  let saveObserver: ((status: 'saving' | 'saved' | 'error', error?: string) => void) | null = null;", 1)
replace_count("sink.port.postMessage({ rate });", "sink.port.postMessage({ rate: rate * speedMultiplier });", 1)
replace_count("      if (msg && msg.rate) {", "      if (msg && msg.reset) {\n        this.pos = 0; this.w = 0; this.lastPost = 0;\n        return;\n      }\n      if (msg && msg.rate) {", 1)
replace_count("const MAX_FRAMES_PER_TICK = 5;", "const MAX_FRAMES_PER_TICK = 24;", 1)
replace_count("Math.round(rate * TARGET_SECONDS) - buffered", "Math.round(rate * speedMultiplier * TARGET_SECONDS) - buffered", 1)
replace_count("Math.floor(((now - wallClockStart) / 1000) * framerate)", "Math.floor(((now - wallClockStart) / 1000) * framerate * speedMultiplier)", 1)
replace_count("  const persistSram = async (): Promise<void> => {", "  let persistQueue: Promise<void> = Promise.resolve();\n  const persistSram = async (): Promise<void> => {", 1)
replace_count("    if (!persistEnabled) return;\n    const bytes = cloneSram();\n    if (!bytes) return;\n    const dir = await opfsDir(namespace, true);\n    if (!dir) return;\n    try {\n      const handle = await dir.getFileHandle('sram.bin', { create: true });\n      const writable = await handle.createWritable();\n      await writable.write(bytes);\n      await writable.close();\n    } catch {\n      // persistence is best-effort\n    }", "    if (!persistEnabled) throw new Error('Browser battery-save storage unavailable');\n    const bytes = cloneSram();\n    if (!bytes) return;\n    const write = async (): Promise<void> => {\n      saveObserver?.('saving');\n      try {\n        const dir = await opfsDir(namespace, true);\n        if (!dir) throw new Error('Browser storage unavailable');\n        const handle = await dir.getFileHandle('sram.bin', { create: true });\n        const writable = await handle.createWritable();\n        await writable.write(bytes);\n        await writable.close();\n        saveObserver?.('saved');\n      } catch (error) {\n        saveObserver?.('error', String(error));\n        throw error;\n      }\n    };\n    const next = persistQueue.then(write);\n    persistQueue = next.catch(() => {});\n    return next;", 1)
replace_count("setInterval(() => void persistSram(), 15000)", "setInterval(() => { if (autoSaveEnabled) void persistSram().catch(console.warn); }, 15000)", 1)
replace_count("      void persistSram();", "      if (autoSaveEnabled) void persistSram().catch(console.warn);", 2)
replace_count("      renderFrame();\n    }\n\n    if (!fpsWindowStart)", "      if (speedMultiplier <= 2 || now - lastDrawTime >= (speedMultiplier <= 4 ? 32 : 65)) {\n        renderFrame();\n        lastDrawTime = now;\n      }\n    }\n\n    if (!fpsWindowStart)", 1)
replace_count("  const instance: MgbaInstance = {", "  const instance: MgbaInstance & {\n    setSpeed(value: number): void;\n    setAutosave(enabled: boolean): void;\n    setSaveObserver(observer: (status: 'saving' | 'saved' | 'error', error?: string) => void): void;\n    flushSave(): Promise<void>;\n    exportSave(): Uint8Array;\n    importSave(data: Uint8Array): Promise<void>;\n    deleteGameCache(): Promise<void>;\n  } = {\n    setSpeed(multiplier: number) {\n      const next = Math.max(1, Math.min(32, Math.round(multiplier)));\n      if (next === speedMultiplier) return;\n      speedMultiplier = next;\n      enqueuedFrames = 0; consumedFrames = 0;\n      sink.port.postMessage({ reset: true });\n      const rate = syncCoreRate();\n      if (rate) sink.port.postMessage({ rate: rate * speedMultiplier });\n      wallClockStart = 0; wallClockFrames = 0;\n      lastDrawTime = 0;\n    },\n    setAutosave(enabled: boolean) { autoSaveEnabled = !!enabled; },\n    setSaveObserver(observer: (status: 'saving' | 'saved' | 'error', error?: string) => void) {\n      saveObserver = observer;\n    },\n    async flushSave() { await persistSram(); },\n    exportSave() {\n      const data = cloneSram();\n      if (!data) throw new Error('No battery save available');\n      return data;\n    },\n    async importSave(data: Uint8Array) {\n      if (!data.length) throw new Error('Empty save file');\n      const ptr = heapAlloc(mod, data);\n      try {\n        if (!mod._mgbawasm_sram_load(ptr, data.length)) throw new Error('Incompatible save file');\n      } finally { mod._free(ptr); }\n      await persistSram();\n    },\n    async deleteGameCache() {\n      autoSaveEnabled = false;\n      await persistQueue;\n      const result = await this.purgeStorage();\n      if (!result.data) throw new Error('No cached data found for this game');\n    },", 1)
p.write_text(s, encoding="utf-8")
print("Web Emu mGBA SDK patched")
